MAINMACHINE := "${MACHINE}"

DEPLOY_DIR_IMAGE_k3r5 = "${TMPDIR}/../tmp-glibc/deploy/images/${MAINMACHINE}"

MACHINE_append = "-k3r5"

# TCLIBC Specifies the GNU standard C library (libc) variant to use during the build process.
TCLIBC = "glibc"

TMPDIR_append = "-k3r5"

SDKPKGSUFFIX = "k3r5-nativesdk"