FROM ubuntu:16.04

# maintainer: volkmann@devpool.net
# url: http://gitea.devpool.net:3000/stevo/oe-buildenv

RUN apt-get update \
    && apt-get install -y gawk wget git-core diffstat unzip texinfo gcc-multilib    \
     build-essential chrpath socat cpio python python3 python3-pip python3-pexpect  \
     xz-utils debianutils iputils-ping libsdl1.2-dev xterm locales repo ncurses-dev \
     screen intltool gengetopt coccinelle faketime bison flex sudo kmod \
	&& localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

# RUN apt-get install -y sudo kmod

ENV LANG en_US.utf8

COPY run.sh /usr/bin/

RUN  chmod 755 /usr/bin/run.sh

ENTRYPOINT ["/usr/bin/run.sh"]
